name: CD to Cloud Run
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: 'Deploy to Cloud Run Job'
      uses: 'google-github-actions/deploy-cloudrun@v2'
      with:
        job: 'property-evaluator-job'
        source: '.'
        region: 'europe-west2'
